### PR TITLE
Use generativity to ensure soundness even with NLL

### LINKED ISSUE #22: Generativity mechanism is unsound 💥
(sorry; I only found this because I was trying to imitate your closure-less generativity)

```rust
fn main() {
    compact_arena::mk_arena!(a, 0);
    compact_arena::mk_arena!(b, 0);
    let mut a: compact_arena::SmallArena<'_, usize> = a;
    let b: compact_arena::SmallArena<'_, usize> = b;

    let ix = a.add(0);
    dbg!(b[ix]);
}
```

This successfully compiles and panics with

```
thread 'main' panicked at 'assertion failed: (i.index as usize) < self.data.len()', D:\usr\.cargo\registry\src\github.com-1ecc6299db9ec823\compact_arena-0.3.1\src\lib.rs:367:9
stack backtrace:
   0: std::sys_common::backtrace::_print
             at src\libstd\sys\windows\backtrace/mod.rs:95
             at src\libstd\sys\windows\backtrace/mod.rs:82
             at src\libstd\sys_common/backtrace.rs:71
   1: std::panicking::default_hook::{{closure}}
             at src\libstd\sys_common/backtrace.rs:59
             at src\libstd/panicking.rs:197
   2: std::panicking::default_hook
             at src\libstd/panicking.rs:211
   3: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:474
   4: std::panicking::begin_panic
             at /rustc/2bafaaf66556ba153fddb00def6d205abb5beff2\src\libstd/panicking.rs:408
   5: <compact_arena::SmallArena<T> as core::ops::index::Index<compact_arena::Idx<u32>>>::index
             at <::std::macros::/panic macros>:3
   6: playground::main
             at src/main.rs:8
   7: std::rt::lang_start::{{closure}}
             at /rustc/2bafaaf66556ba153fddb00def6d205abb5beff2\src\libstd/rt.rs:64
   8: std::panicking::try::do_call
             at src\libstd/rt.rs:49
             at src\libstd/panicking.rs:293
   9: _rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:87
  10: std::rt::lang_start_internal
             at src\libstd/panicking.rs:272
             at src\libstd/panic.rs:388
             at src\libstd/rt.rs:48
  11: std::rt::lang_start
             at /rustc/2bafaaf66556ba153fddb00def6d205abb5beff2\src\libstd/rt.rs:64
  12: main
  13: _tmainCRTStartup
  14: mainCRTStartup
  15: unit_addrs_search
  16: unit_addrs_search
error: process didn't exit successfully: `target\debug\playground.exe` (exit code: 101)
```

and segfaults when compiled in release mode with

```
error: process didn't exit successfully: `target\release\playground.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

(Windows)

### PR DESCRIPTION
**Pull request by llogiq**
It was recently found out that edition 2018 NLL doesn't ensure lifetime uniqueness with the current setup. This uses a slightly different scheme, which unfortunately makes `InvariantLifetime`part of the public API, but that's a small price to pay for soundness.

This fixes #22

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -81,8 +81,18 @@ use core::marker::PhantomData;
 #[cfg(feature = "alloc")]
 use std::error::Error;
 
+/// This is one part of the secret sauce that ensures that indices from
+/// different arenas cannot be mixed. You should never need to use this type in
+/// yout code.
```
Comment (Kerollmops) [inline src/lib.rs]: `s/yout/your/`

File: src/lib.rs [hunk 2]
```diff
@@ -81,8 +81,18 @@ use core::marker::PhantomData;
...
 #[derive(Copy, Clone, PartialOrd, PartialEq, Eq)]
-struct InvariantLifetime<'a>(PhantomData<fn(&'a ()) -> &'a ()>);
+pub struct InvariantLifetime<'a>(PhantomData<fn(&'a ()) -> &'a ()>);
+
+/// Create an invariant lifetime. This is one part of the secret sauce that
+/// ensures that indices from different arenas cannot be mixed. You should
+/// never need to use this type in yout code.
```
Comment (Kerollmops) [inline src/lib.rs]: `s/yout/your`

Comment (llogiq) [reply src/lib.rs]: Thanks, fixed.

File: src/lib.rs (hunk 1 above)
Comment (llogiq) [reply src/lib.rs]: :+1:
